name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "release"

env:
  NUGET_REPO_URL: "https://api.nuget.org/v3/index.json"
  VERSION: 1.6.16.${{ github.run_number }}

jobs:
  publish:
    name: 🚚 Prepare new release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Sets environment variables - branch-name
        uses: nelonoel/branch-name@v1.0.1
      - name: Sets environment variables - Nerdbank.GitVersioning
        uses: dotnet/nbgv@master
        with:
          setAllVars: true
      - name: Build
        run: dotnet build -c Release OasReader.sln -p:UseSourceLink=true -p:PackageVersion="${{ env.VERSION }}" -p:Version="${{ env.VERSION }}"
      - name: Move packages
        shell: pwsh
        run: Get-ChildItem -Filter *.nupkg -Recurse | ForEach-Object { Move-Item -Path $_ -Destination . }
      - name: Publish artifacts
        uses: actions/upload-artifact@v5
        with:
          name: Packages
          path: |
            **/*.nupkg
            README.md
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: christian.helle
      - name: Push packages to NuGet
        run: dotnet nuget push **/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source ${{ env.NUGET_REPO_URL }} --no-symbols
      - name: Create tag
        uses: actions/github-script@v8
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.VERSION }}",
              sha: context.sha
            })

